name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "92d6db8d-074e-4c53-bd6c-dfb6d1071a52"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "95dfc96764c94214ac56271f2bb253e8"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
