name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "bbb05ed4-02dd-48f3-8c7f-e90d3d5d1318"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "b8ab4d571ba949c8808d9ff6d377fc5f"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
